# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('wagtailimages', '0010_change_on_delete_behaviour'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEntry',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', models.CharField(max_length=140, verbose_name='Beskrivelse')),
                ('details', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True, verbose_name='Detaljer')),
                ('date', models.DateField(auto_now=True, verbose_name='Dato')),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Bilde til nyhetsstrømmen')),
            ],
            options={
                'verbose_name': 'Nyhet',
                'verbose_name_plural': 'Nyheter',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsEntryIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Nyhetsoversikt',
                'verbose_name_plural': 'Nyhetsoversikter',
            },
            bases=('wagtailcore.page',),
        ),
    ]
