# Generated by Django 5.2.12 on 2026-03-29 22:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_newsentryindex_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsentryindex',
            name='sidepanel',
            field=wagtail.fields.StreamField([('eventviewer', 3), ('linkviewer', 12), ('videoembed', 15)], blank=True, block_lookup={0: ('home.models.UpcomingEventCountChoiceField', (), {'label': 'Antall synlige aktiviteter'}), 1: ('home.models.UpcomingEventCentreChoiceField', (), {'label': 'Hvilket senter?'}), 2: ('wagtail.blocks.BooleanBlock', (), {'label': 'Langtidsvisning', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('count', 0), ('centre_code', 1), ('display_all', 2)]], {'label': 'Vis kommende aktiviteter'}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Ekstern lenke', 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Intern lenke', 'required': False}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Dokument- lenke', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('external_url', 4), ('page_link', 5), ('document', 6)]], {'label': 'lenke', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Vær kortfattet, slik at teksten vises riktig.', 'label': 'Overskrift', 'max_length': 50}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Vær kortfattet, slik at teksten vises riktig.', 'label': 'Undertittel', 'max_length': 50}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Velg ikonnavn fra http://fontawesome.io/cheatsheet/', 'label': 'Ikon', 'max_length': 50}), 11: ('wagtail.blocks.StructBlock', [[('link', 7), ('caption', 8), ('subcaption', 9), ('icon', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'icon': 'link', 'label': 'Lenke- fremviser', 'template': 'home/blocks/sidepanel_links.html'}), 13: ('wagtail.blocks.TextBlock', (), {'label': 'Seksjonstittel', 'required': True}), 14: ('wagtail.blocks.TextBlock', (), {'help_text': 'I Youtube, velg "share" -> "embed" -> "copy". Lim inn teksten her.', 'label': 'Youtube embed-kode (video-id)', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('caption', 13), ('video_id', 14)]], {'label': 'Youtube- video'})}, default='', verbose_name='sidepanel'),
        ),
    ]
