# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 11:43
from __future__ import unicode_literals

from django.db import migrations
import home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('gcal', '0006_auto_20170120_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='body',
            field=wagtail.core.fields.StreamField((('h2styled', wagtail.core.blocks.CharBlock(classname='title', icon='title', label='stilisert overskrift')), ('h2', wagtail.core.blocks.CharBlock(classname='title', icon='title', label='overskrift stor')), ('h3', wagtail.core.blocks.CharBlock(classname='title', icon='title', label='overskrift mindre')), ('h4', wagtail.core.blocks.CharBlock(classname='title', icon='title', label='overskrift minst')), ('hr', wagtail.core.blocks.StructBlock(())), ('intro', wagtail.core.blocks.RichTextBlock(icon='pilcrow', label='introduksjon')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow', label='paragraf')), ('pullquote', wagtail.core.blocks.StructBlock((('quote', wagtail.core.blocks.RichTextBlock(label='Sitat')), ('attribution', wagtail.core.blocks.CharBlock(label='Tilegnelse', required=False))), label='Sitat')), ('aligned_image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock(label='Bilde')), ('caption', wagtail.core.blocks.RichTextBlock(label='Bildetekst')), ('alignment', home.models.ImageFormatChoiceBlock(label='Justering'))), icon='image', label='Justert bilde')), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse', label='dokument')), ('markdown', home.models.MarkDownBlock(label='markdown')), ('news_feed', wagtail.core.blocks.StructBlock((('count', home.models.NewsFeedCountChoiceField(label='Antall nyheter i visning')),), icon='grip', label='Siste nyheter'))), default='', verbose_name='hovedinnhold'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='body',
            field=wagtail.core.fields.StreamField((('h2styled', wagtail.core.blocks.CharBlock(classname='title', icon='title', label='stilisert overskrift')), ('h2', wagtail.core.blocks.CharBlock(classname='title', icon='title', label='overskrift stor')), ('h3', wagtail.core.blocks.CharBlock(classname='title', icon='title', label='overskrift mindre')), ('h4', wagtail.core.blocks.CharBlock(classname='title', icon='title', label='overskrift minst')), ('hr', wagtail.core.blocks.StructBlock(())), ('intro', wagtail.core.blocks.RichTextBlock(icon='pilcrow', label='introduksjon')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow', label='paragraf')), ('pullquote', wagtail.core.blocks.StructBlock((('quote', wagtail.core.blocks.RichTextBlock(label='Sitat')), ('attribution', wagtail.core.blocks.CharBlock(label='Tilegnelse', required=False))), label='Sitat')), ('aligned_image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock(label='Bilde')), ('caption', wagtail.core.blocks.RichTextBlock(label='Bildetekst')), ('alignment', home.models.ImageFormatChoiceBlock(label='Justering'))), icon='image', label='Justert bilde')), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse', label='dokument')), ('markdown', home.models.MarkDownBlock(label='markdown')), ('news_feed', wagtail.core.blocks.StructBlock((('count', home.models.NewsFeedCountChoiceField(label='Antall nyheter i visning')),), icon='grip', label='Siste nyheter'))), default='', verbose_name='hovedinnhold'),
        ),
    ]
