# Generated by Django 2.0.8 on 2018-08-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcal', '0008_wagtail_1-12'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='google_location',
        ),
    ]
