# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 07:02
from __future__ import unicode_literals

from django.db import migrations
import home.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sidepanel_linkview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('h2styled', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='stilisert overskrift')), ('h2', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='overskrift stor')), ('h3', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='overskrift mindre')), ('h4', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='overskrift minst')), ('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', label='introduksjon')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', label='paragraf')), ('pullquote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.TextBlock('sitat')), ('attribution', wagtail.wagtailcore.blocks.CharBlock('tilegnelse'))), label='Sitat')), ('aligned_image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(label='Bilde')), ('caption', wagtail.wagtailcore.blocks.RichTextBlock(label='Bildetekst')), ('alignment', home.models.ImageFormatChoiceBlock(label='Justering'))), icon='image', label='Justert bilde')), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', label='dokument')), ('news_feed', wagtail.wagtailcore.blocks.StructBlock((('count', home.models.NewsFeedCountChoiceField(label='Antall nyheter i visning')),), icon='grip', label='Siste nyheter'))), default='', verbose_name='hovedinnhold'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='headingpanel',
            field=wagtail.wagtailcore.fields.StreamField((('quicklinks', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('link', wagtail.wagtailcore.blocks.StructBlock((('external_url', wagtail.wagtailcore.blocks.URLBlock(label='Ekstern lenke', required=False)), ('page_link', wagtail.wagtailcore.blocks.PageChooserBlock(label='Intern lenke', required=False)), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(label='Dokument- lenke', required=False))), label='lenke', required=True)), ('caption', wagtail.wagtailcore.blocks.CharBlock(help_text='Vær kortfattet, slik at teksten vises riktig.', label='Overskrift', max_length=50)), ('subcaption', wagtail.wagtailcore.blocks.CharBlock(help_text='Vær kortfattet, slik at teksten vises riktig.', label='Undertittel', max_length=50)), ('icon', wagtail.wagtailcore.blocks.CharBlock(help_text='Velg ikonnavn fra http://fontawesome.io/cheatsheet/', label='Ikon', max_length=50)))), icon='link', label='Snarveis- panel', template='home/blocks/quicklink_list.html')), ('imageslider', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(label='Bilde')),)), icon='image', label='Bilde- karusell', template='home/blocks/imageslider_list.html')), ('bannerimage', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(label='Bilde')),), label='Strekker seg over hele skjermen. OBS: 2048x500 piksler!'))), default='', verbose_name='overpanel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sidepanel',
            field=wagtail.wagtailcore.fields.StreamField((('eventviewer', wagtail.wagtailcore.blocks.StructBlock((('count', home.models.UpcomingEventCountChoiceField(label='Antall synlige aktiviteter')), ('centre_code', home.models.UpcomingEventCentreChoiceField(label='Hvilket senter?'))), label='Vis kommende aktiviteter')), ('linkviewer', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('link', wagtail.wagtailcore.blocks.StructBlock((('external_url', wagtail.wagtailcore.blocks.URLBlock(label='Ekstern lenke', required=False)), ('page_link', wagtail.wagtailcore.blocks.PageChooserBlock(label='Intern lenke', required=False)), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(label='Dokument- lenke', required=False))), label='lenke', required=True)), ('caption', wagtail.wagtailcore.blocks.CharBlock(help_text='Vær kortfattet, slik at teksten vises riktig.', label='Overskrift', max_length=50)), ('subcaption', wagtail.wagtailcore.blocks.CharBlock(help_text='Vær kortfattet, slik at teksten vises riktig.', label='Undertittel', max_length=50)), ('icon', wagtail.wagtailcore.blocks.CharBlock(help_text='Velg ikonnavn fra http://fontawesome.io/cheatsheet/', label='Ikon', max_length=50)))), icon='link', label='Lenke- fremviser', template='home/blocks/sidepanel_links.html'))), default='', verbose_name='sidepanel'),
        ),
    ]
