# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 18:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import home.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=200, verbose_name='Oppsummering')),
                ('description', models.CharField(max_length=1000, verbose_name='Beskrivelse')),
                ('public', models.BooleanField(verbose_name='Offentlig kalender')),
                ('sync_token', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('code', models.CharField(max_length=3, verbose_name='Kode')),
                ('address', models.TextField(verbose_name='Addresse')),
                ('description', models.CharField(max_length=200, verbose_name='Beskrivelse')),
                ('information', wagtail.wagtailcore.fields.StreamField((('h2', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='overskrift stor')), ('h3', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='overskrift mindre')), ('h4', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='overskrift minst')), ('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', label='introduksjon')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', label='paragraf')), ('pullquote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.TextBlock('sitat')), ('attribution', wagtail.wagtailcore.blocks.CharBlock('tilegnelse'))), label='Sitat')), ('aligned_image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(label='Bilde')), ('caption', wagtail.wagtailcore.blocks.RichTextBlock(label='Bildetekst')), ('alignment', home.models.ImageFormatChoiceBlock(label='Justering'))), icon='image', label='Justert bilde')), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', label='dokument'))), null=True, verbose_name='information')),
                ('tlf', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('event_id', models.CharField(max_length=1024)),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('end', models.DateTimeField(verbose_name='Slutt')),
                ('summary', models.CharField(max_length=200, verbose_name='Oppsummering')),
                ('full_day', models.BooleanField(verbose_name='Full dag')),
                ('recurrence', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('recurring_event_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', wagtail.wagtailcore.fields.RichTextField()),
                ('creator', models.CharField(max_length=100, verbose_name='Opprettet av')),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendar', to='gcal.Calendar', verbose_name='Kalender')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='calendar',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centre', to='gcal.Centre', verbose_name='Senter'),
        ),
    ]
