# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=200, verbose_name='Oppsummering')),
                ('description', models.CharField(max_length=1000, verbose_name='Beskrivelse')),
                ('public', models.BooleanField(verbose_name='Offentlig kalender')),
                ('sync_token', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Kode')),
                ('name', models.CharField(max_length=200, verbose_name='Navn')),
                ('address', models.TextField(verbose_name='Addresse')),
                ('description', models.CharField(max_length=200, verbose_name='Beskrivelse')),
                ('tlf', models.CharField(blank=True, max_length=18, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bilde')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('end', models.DateTimeField(verbose_name='Slutt')),
                ('summary', models.CharField(max_length=400, verbose_name='Oppsummering')),
                ('full_day', models.BooleanField(verbose_name='Full dag')),
                ('html_link', models.URLField(blank=True, null=True, verbose_name='Google lenke')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar', to='gcal.Calendar', verbose_name='Kalender')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centre', to='gcal.Centre', verbose_name='Senter'),
        ),
    ]
