# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 06:42
from __future__ import unicode_literals

from django.db import migrations
import home.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('gcal', '0004_auto_20170104_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('h2styled', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='stilisert overskrift')), ('h2', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='overskrift stor')), ('h3', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='overskrift mindre')), ('h4', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='overskrift minst')), ('hr', wagtail.wagtailcore.blocks.StructBlock(())), ('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', label='introduksjon')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', label='paragraf')), ('pullquote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.TextBlock(label='Sitat')), ('attribution', wagtail.wagtailcore.blocks.CharBlock(label='Tilegnelse', required=False))), label='Sitat')), ('aligned_image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(label='Bilde')), ('caption', wagtail.wagtailcore.blocks.RichTextBlock(label='Bildetekst')), ('alignment', home.models.ImageFormatChoiceBlock(label='Justering'))), icon='image', label='Justert bilde')), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', label='dokument')), ('markdown', home.models.MarkDownBlock(label='markdown')), ('news_feed', wagtail.wagtailcore.blocks.StructBlock((('count', home.models.NewsFeedCountChoiceField(label='Antall nyheter i visning')),), icon='grip', label='Siste nyheter'))), default='', verbose_name='hovedinnhold'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('h2styled', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='stilisert overskrift')), ('h2', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='overskrift stor')), ('h3', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='overskrift mindre')), ('h4', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', label='overskrift minst')), ('hr', wagtail.wagtailcore.blocks.StructBlock(())), ('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', label='introduksjon')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', label='paragraf')), ('pullquote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.TextBlock(label='Sitat')), ('attribution', wagtail.wagtailcore.blocks.CharBlock(label='Tilegnelse', required=False))), label='Sitat')), ('aligned_image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(label='Bilde')), ('caption', wagtail.wagtailcore.blocks.RichTextBlock(label='Bildetekst')), ('alignment', home.models.ImageFormatChoiceBlock(label='Justering'))), icon='image', label='Justert bilde')), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', label='dokument')), ('markdown', home.models.MarkDownBlock(label='markdown')), ('news_feed', wagtail.wagtailcore.blocks.StructBlock((('count', home.models.NewsFeedCountChoiceField(label='Antall nyheter i visning')),), icon='grip', label='Siste nyheter'))), default='', verbose_name='hovedinnhold'),
        ),
    ]
